services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development

volumes:
  bundle: